#pragma once

class MYINFO
{
public:
	BOOL mWarningDisplayState;
	float mWarningDisplayTime;
	float mScreenXPosSize;
	float mScreenYPosSize;
	float mFPS; // Adãugãm membrul pentru FPS
	int mScreenSort;
	int mScreenXSize;
	int mScreenYSize;
	int mServerType;
	char uID[MAX_USER_ID_LENGTH];
	char uPassword[MAX_USER_PASSWORD_LENGTH];
	int uUserSort;
	//int uGoodFellow;
	//int uLoginPlace;
	int uLoginPremium;
	int mSecondLoginSort;
	char mMousePassword[5];
	//int mSecondLoginSort1;
	//int mSecondLoginSort2;
	int mWebItem[50];
	AVATAR_INFO mSelectAvatarInfo[3];
	AVATAR_INFO mCreateAvatarInfo;
	int mGiftItem[10][2];
	AVATAR_INFO mAvatarInfo;
	int mAvatarEffectValue[MAX_AVATAR_EFFECT_SORT_NUM][2];
	float mElementValue[MAX_AVATAR_EFFECT_SORT_NUM];
	int mLegendaryEffectValue[24][3];
	char mPartyInfo[5][MAX_AVATAR_NAME_LENGTH];
	BOOL mMoveZoneState;
	int mMoveZoneSort;
	int mMoveZoneValue;
	int mPreviousZoneNumber;
	int mPresentZoneNumber;
	int mNextZoneNumber;
	ACTION_INFO mAction;
	BOOL mCheckQuestCall;
	float mQuestCallPostTime;
	int mQuestCallPresentState;
	int mQuestCallNPCNumber;
	int mQuestCallSpeechIndex;
	int mMaWhangGungTime;
	BOOL mCheckSendActionPacket;
	float mSendActionPacketPostTime;
	int mNetworkLock;
	float mSendItemPacketPostTime;
	int mDemandGuildInfoSort;
	int mTeacherStudentState;
	float mBGMPlayPostTime;
	int mHotKeyPage;
	int mHotKeyIndex;
	int mSelectObjSort;
	int mSelectObjIndex;
	int mSelectObjUniqueNumber;
	int mTotalTargetNum;
	int mTargetSort[12];
	int mTargetServerIndex[5];
	int mKRUnknownAttackPacket;
	DWORD mTargetUniqueNumber[5];
	/*int mTargetSort[10];
	int mTargetServerIndex[5];
	DWORD mTargetUniqueNumber[5];
	int mKRUknown3[3];*/
	float mUnknownTime;
	float mSkillRunPostTime1;
	BOOL mCheckHelpConditionEffect;
	int mHelpConditionEffectIndex;
	int mLevelBattleZoneNumberForMove;
	BOOL mCheckLevelBattleOpenGateEffect;
	float mLevelBattleOpenGateEffectFrame;
	BOOL mCheckLevelBattle49TypeOpenEffect;
	int mLevelBattle49TypeOpenEffectImageIndex;
	int mLevelBattle49TypeRemainTime;
	BOOL mCheckLevelBattle49TypeInfo;
	int mLevelBattle49TypeInfo[4];
	BOOL mCheckLevelBattle51TypeOpenEffect;
	int mLevelBattle51TypeOpenEffectImageIndex;
	BOOL mCheckLevelBattle53TypeOpenEffect;
	int mLevelBattle53TypeOpenEffectImageIndex;
	BOOL mCheckLevelBattle53TypeEffect1;
	float mLevelBattle53TypeEffectFrame1;
	BOOL mCheckLevelBattle53TypeEffect2;
	float mLevelBattle53TypeEffectFrame2;
	BOOL mCheckZone038Effect1;
	float mZone038EffectFrame1;
	BOOL mCheckZone038Effect2;
	float mZone038EffectFrame2;
	BOOL mCheckZone037Effect1;
	float mZone037EffectFrame1;
	BOOL mCheckZone037Effect2;
	float mZone037EffectFrame2;
	BOOL mCheckZone175TypeGateEffect1[10];
	BOOL mCheckZone175TypeGateEffect2[10];
	float mZone175TypeGateFrame[10];
	BOOL mCheckZone194BattleOpenGateEffect;
	float mZone194BattleOpenGateEffectFrame;
	int mZone194BattleRemainTime;
	int mZone194BattleInfo[4];
	BOOL mCheckZone196Effect1;
	float mZone196EffectFrame1;
	BOOL mCheckZone196Effect2;
	float mZone196EffectFrame2;
	BOOL mCheck267TypeOpenGateEffect;
	float m267TypeOpenGateEffectFrame;
	int m267TypeRemainTime;
	BOOL mCheck267TypeInfo;
	int m267TypeInfo[4];
	BOOL mCheckZone291Effect;
	float mZone291EffectFrame;
	int mHoisundoZoneNumberForMove;
	BOOL mCheckZone297TypeGateEffect1[4];
	BOOL mCheckZone297TypeGateEffect2[4];
	float mZone297TypeGateFrame1[4];
	float mZone297TypeGateFrame2[4];
	BOOL mCheck297TypeInfo;
	int mZone297TypeMonsterInfo[4];
	BOOL mCheckZone200TypeGateEffect1[4];
	BOOL mCheckZone200TypeGateEffect2[4];
	float mZone200TypeGateFrame1[4];
	float mZone200TypeGateFrame2[4];
	BOOL mCheck200TypeInfo;
	int mZone200TypeMonsterInfo[4];
	int mEatDrugStateForAuto;
	int mUseInventoryPage;
	int mUseInventoryIndex;
	int iTribeCallType;
	BOOL bIsUseContinueSkill;
	BOOL mCheckZone88TypeGateEffect[4];
	float mZone88TypeGateFrame[4];
	int mZone88OpenGateState[4];
	BOOL mZone88TypeCenterEffect[2];
	float mZone88TypeCenterFrame[2];
	BOOL mCheckFourGuildTypeGateEffect1;
	BOOL mCheckFourGuildTypeGateEffect2;
	BOOL mCheckFourGuildTypeGateEffect3;
	BOOL mCheckFourGuildTypeGateEffect4;
	float mZoneFourGuildTypeGateFrame1;
	float mZoneFourGuildTypeGateFrame2;
	float mZoneFourGuildTypeGateFrame3;
	float mZoneFourGuildTypeGateFrame4;
	BOOL mCheckZone5TypeGateEffect2[10];
	BOOL mCheckZone5TypeGateEffect1[10];
	float mZone5TypeGateFrame[10];
	BOOL mCheckZone54TypeGateEffect[4];
	float mZone54TypeGateFrame[4];
	BOOL mCheckLevelBattle319TypeOpenEffect;
	BOOL mCheckLevelBattle319TypeInfo;
	int mLevelBattle319TypeOpenEffectImageIndex;
	int mLevelBattle319TypeRemainTime;
	int mLevelBattle319TypeInfo[4];
	int mZone319TypeTop20RankTribe[20];
	int mZone319TypeTop20RankScore[20];
	char mZone319TypeTop20RankName[20][13];
	int mZone319TypeLineUpRank[20];
	BOOL mCheck319TypeTop20RankState;
	BOOL mShowTop4Rank;
	int mGeneralExperienceUpRatio;
	int mItemDropUpRatio;
	int mKillOtherTribeAddValue;
	int mPvPDamageUpRatio;
	int mPvMDamageUpRatio;
	int mMaxPotionEventNum;
	int mPvPDamageUpTribe;
	int mPvMDamageUpTribe;
	int mMaxPotionEventTribe;
	BOOL mbIsPVPDie;
	int mStatBalance;
	int mMixSkillWaitingTime[2];
	int mBottleIndex;
	int unk_CD8C[4];
	int unk_CDFC;
	int unk_129;
	int unk_130;
	int unk_131;
	int unk_132;
	int mClientTickNew;
	int mServerMon;
	int mServerDay;
	int mServerHour;
	int mServerMin;
	char mServerWDay[20];
	float mTrapPosition[5][3];
	int Rcmd1;
	int Rcmd2;
	int Rcmd3;
	int mOnlineAutoTime;
	float mPostAutoTime;
	int mPing;
	DWORD mSkillForProtect[40][2];
	DWORD mSkillProtectPostTime;


	BOOL Init();
	void Free();
	void InitForEnterZone();
	void AdjustScreenCoord(int tUINum, int mX, int mY, int* tX, int* tY);
	int ReturnQuestPresentState();
	int ReturnQuestNextNPCNumber();
	BOOL ReturnQuestEndConditionState();
	void DrawForQuestCall();
	int GetSelectAvatarName(char* tAvatarName);
	int ButtonDownForSkill(int a2);
	void A000(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	void A001();
	void A002_1(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	void A002_2(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	void A003();
	void A004();
	void A005(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	void A006(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	void A007(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	void A008();
	void A010();
	void A011(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	void A014();
	void A015();
	void A016(int tSkillNumber);
	void A017();
	void A018();
	void A019();
	void A021();
	void A022();
	void A023();
	BOOL A024(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A031(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A033(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A034(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A039(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A040(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A041(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A042(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A043(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A044(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A045(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A046(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A047(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A049(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A050(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A051(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A052(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A053(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A055(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A056(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A057(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A058(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A059(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A061(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A062(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A063(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8, int a9);
	void A064(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8, int a9);
	void A065(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8, int a9);
	BOOL A066(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A067(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A068(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A069(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A070(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A071(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A072(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A073(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A074(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A075(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A076(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A081(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A082(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A083(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A085(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A086(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A087(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A088(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A089(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	BOOL A090(float tLocation[3], int a3, int a4, int a5, int a6, int a7, int a8);
	void A091();
	void CheckAttackSpeed(int tSkillNumber, float tAttackSpeed, int tProtectValue);
	int ReturnProtectValue(int tSkillNumber);
	BOOL CheckPossibleAttackForProtect(int tSkillNumber);
	void CheckPossibleKeyboardAttackForProtect();
	

};
extern MYINFO mMYINFO;